### PR TITLE
Add the umd directory to files in package.json

### PR DESCRIPTION
**Pull request by hnqlv**
@benhowdle89 great stuff! 

I changed the `main` entry point to the uncompiled version and added the dist file to `files` array in package. The dist file will become available on npmcdn.

### CODE REVIEW

**Comment by hnqlv** [comment]
@benhowdle89 don't forget to npm publish it so we can get the changes on npmcdn too. Thanks 👍

**Comment by benhowdle89** [comment]
When people do `npm install grade-js`, what will `import Grade from 'grade-js'` now point to? Is the compiled or the uncompiled version?

**Comment by hnqlv** [comment]
@benhowdle89 the uncompiled version which make sense since you're probably using a module blunder.

**Comment by benhowdle89** [comment]
Absolutely true. Will probably add something to the README saying that it'll need to go through something like Babel for ES2015 support

**Comment by hnqlv** [comment]
@benhowdle89 yes that's a good idea. Also if you're using CommonJS modules in the browser you're going to need browserify or webpack. Using just babel doing `import Grade from 'grade-js'` won't work 😊

**Pull request merged**
